default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: postgres
  user: postgres


development:
  <<: *default
  database: netshowme_development


test:
  <<: *default
  database: netshowme_test
 

production:
  <<: *default
  database: netshowme_production
  username: netshowme
  password: <%= ENV['netshowme_DATABASE_PASSWORD'] %>