default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: postgres
  user: postgres


development:
  <<: *default
  database: netshowme_development


test:
  <<: *default
  database: netshowme_test
 

configure :production do
  db = URI.parse(ENV['DATABASE_URL'] || 'postgres:///postgres/netshowme_production')
 
  set :database, {
    adapter:  'postgresql',
    host:     db.host,
    username: db.user,
    password: db.password,
    database: db.path[1..-1],
    encoding: 'utf8'
  }
end